openapi: 3.0.0
info:
  title: Meter Reading API
  version: 1.0.0
  description: >-
    Reads a stringifyied image and AI translates image to serial, meterreading
    and possiblibly obis.
  contact:
    name: Edgar Jung
    email: edgar.jung@elropro.com
servers:
  - url: https://makohub.de
    description: Productive Server
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MeterUploadRequest:
      type: object
      properties:
        image:
          type: string
          description: Base64-encoded image or raw string content
      required:
        - image
    MeterUploadResponse:
      type: object
      properties:
        device:
          type: string
          description: 'Herstellergerätenummer '
        obis:
          type: string
          description: full obis code
        scanObisRead:
          type: string
        reading:
          type: string
        serial:
          type: string
      required:
        - device
        - obis
        - scanObisRead
        - reading
        - serial
paths:
  /meter/upload:
    post:
      summary: Upload a meter image for recognition
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeterUploadRequest'
      responses:
        '200':
          description: Successful meter recognition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeterUploadResponse'
