openapi: 3.0.3
info:
  title: AI Meter Image Analysis
  description: >-
    Upload a meter image to AI. AI processes information out of the picture an
    sends back the meter serial code and meter reading. This can be easly used
    for automated integration in Backend systems like SAP, Wilken, Schleupen or
    others
  termsOfService: ''
  contact:
    email: edgar.jung@elropro.com
    name: Edgar Jung
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about spec
  url: ''
servers: []
tags:
  - name: Default
    description: ''
paths: {}
components:
  schemas: {}
  securitySchemes: {}
