openapi: 3.0.0
info:
  title: Meter Reading API
  version: 1.0.0
  description: "Reads a stringifyed image and AI translates image to serial, meterreading and possiblibly obis. You may use productive environment **https://makohub.de**. #token#. Please set **Timeout** at least to **120 seconds** as the recognition needs time - and we have a lot of detection requests at the same time.\r\n\r\nComplete Example in PHP \r\n\r\n\r\n    $ch = curl_init();\r\n    $headers = array(\r\n        'Accept: application/json',\r\n        'Content-Type: application/json',\r\n        'Authorization: bearer bGVsbG86d29ybGQ=',\r\n    );\r\n        \r\n    $cont = file_get_contents(\"c:/temp/26461398_IMG_4356.jpg\");\r\n    $b64  = base64_encode($cont);\r\n    \r\n    curl_setopt($ch, CURLOPT_URL, \"https://makohub.de/meter/upload\");\r\n    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);\r\n    curl_setopt($ch, CURLOPT_HEADER, 0);\r\n    \r\n    $body[\"image\"] = $b64;\r\n    \r\n    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, \"POST\");\r\n    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($body));\r\n    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);\r\n    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);\r\n    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);\r\n           \r\n    // Timeout in seconds\r\n    curl_setopt($ch, CURLOPT_TIMEOUT, 180);\r\n    \r\n    $ret = curl_exec($ch);\r\n    $err = curl_error($ch); \r\n    $code = curl_getinfo($ch,CURLINFO_HTTP_CODE);\r\n    if($code!=200 || !empty($err))\r\n    {\r\n      \r\n      if(!empty($ret)) echo \"Error: \". print_r($ret,true);\r\n      if(!empty($err)) echo \"error: \". curl_error($ch);\r\n      die(-1);\r\n    }\r\n    \r\n     print_r($ret);"
  contact:
    name: Edgar Jung
    email: edgar.jung@elropro.com
servers:
  - url: https://makohub.de
    description: Productive Server
    variables: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MeterUploadRequest:
      type: object
      properties:
        image:
          type: string
          description: Base64-encoded image or raw string content
          examples:
            - /9j/4AAQSkZJRgABAQ...
          example: /9j/4AAEDOMGKRfjAIG....
      required:
        - image
    MeterUploadResponse:
      type: object
      properties:
        device:
          type: string
          description: Type of Device/Input
          enum:
            - digital
            - analog
            - readingCard
          examples:
            - digital
          example: digital
        obis:
          type: string
          description: full obis code, matched with edi@energy code list
          examples:
            - 7-20:3.0.0
          example: 1-8:1.0.0
        scanObisRead:
          type: string
          description: Obis on the device, if there is any
          examples:
            - '180'
            - 1.8.0
          example: 1.8.0
        reading:
          type: string
          description: Reading from the meter device. May have leading zeroes
          default: '0'
          examples:
            - '003942'
          example: 4864
        serial:
          type: string
          description: Manuafacturer Serial Number
          examples:
            - 7ELS2535764232
          example: 1ISK298302994
        status:
          type: string
          enum:
            - success
            - error
          description: Status of operation
          default: success
        meterreadscore:
          type: number
          description: Score, the meterreading is done by AI . 1.0 highest = 100%
          example: 0.99334
          maximum: 1
          minimum: 0
        meternumberscore:
          type: number
          description: Score, the device number is properly detected, highest 1.0 = 100%
          example: 0.99984
          maximum: 1
          minimum: 0
      required:
        - device
        - obis
        - scanObisRead
        - reading
        - serial
        - status
        - meterreadscore
        - meternumberscore
    MeterError:
      type: object
      properties:
        code:
          type: number
          description: Errorcode
          example: 504
        message:
          type: string
          description: ErrorDescription
          example: timeout from AI machine - try again later - too busy
        success:
          type: boolean
          default: false
      required:
        - code
        - message
        - success
  headers:
    header-1:
      required: false
      description: ''
      schema:
        type: string
  responses: {}
  parameters: {}
paths:
  /meter/upload:
    post:
      summary: Upload a meter image for recognition
      x-timeout: 120000
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeterUploadRequest'
      responses:
        '200':
          description: Successful meter recognition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeterUploadResponse'
        '500':
          description: Error with Text, if request breaks
          content: {}
          headers: {}
        '504':
          description: >-
            AI recognition takes too long. Make sure to set your reqest timeout
            to 120 seconds
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeterError'
