openapi: 3.0.0
info:
  title: Meter Reading API
  version: 1.0.0
  description: "Reads a stringifyied image and AI translates image to serial, meterreading and possiblibly obis.\r\nYou may use productive environment **https://makohub.de**. #token#". Please set **Timeout** at least to **120 seconds** as the recognition needs time - and we have a lot of detection
  requests at the same time.
  contact:
    name: Edgar Jung
    email: edgar.jung@elropro.com
servers:
  - url: https://makohub.de
    description: Productive Server
    variables: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MeterUploadRequest:
      type: object
      properties:
        image:
          type: string
          description: Base64-encoded image or raw string content
          examples:
            - /9j/4AAQSkZJRgABAQ...
          example: /9j/4AAEDOMGKRfjAIG....
      required:
        - image
    MeterUploadResponse:
      type: object
      properties:
        device:
          type: string
          description: Type of Device/Input
          enum:
            - digital
            - analog
            - readingCard
          examples:
            - digital
          example: digital  
        obis:
          type: string
          description: full obis code, matched with edi@energy code list
          examples:
            - 7-20:3.0.0
          example: 1-8:1.0.0
        scanObisRead:
          type: string
          description: Obis on the device, if there is any
          examples:
            - '180'
            - 1.8.0
          example: 1.8.0
        reading:
          type: string
          description: Reading from the meter device. May have leading zeroes
          default: '0'
          examples:
            - '003942'
          example:  04864
        serial:
          type: string
          description: Manuafacturer Serial Number
          examples:
            - 7ELS2535764232
          example: 1ISK298302994
        status:
          type: string
          enum:
            - success
            - error
          description: Status of operation
          default: success
        meterreadscore:
          type: number
          description: Score, the meterreading is done by AI . 1.0 highest = 100%
          example: 0.99334
          maximum: 1
          minimum: 0
        meternumberscore:
          type: number
          description: Score, the device number is properly detected, highest 1.0 = 100%
          example: 0.99984
          maximum: 1
          minimum: 0
      required:
        - device
        - obis
        - scanObisRead
        - reading
        - serial
        - status
        - meterreadscore
        - meternumberscore
  headers:
    header-1:
      required: false
      description: ''
      schema:
        type: string
  responses: {}
  parameters: {}
paths:
  /meter/upload:
    post:
      summary: Upload a meter image for recognition
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeterUploadRequest'
      responses:
        '200':
          description: Successful meter recognition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeterUploadResponse'
        '500':
          description: Error with Text, if request breaks
          content: {}
          headers: {}
        '504':
          description: >-
            AI recognition takes too long. Make sure to set your reqest timeout
            to 120 seconds
          content: {}
          headers: {}
