openapi: 3.0.3
info:
  title: New Spec - OpenAPI 3.0
  description: ELRON Case
  termsOfService: ''
  contact:
    email: ''
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about spec
  url: ''
servers: []
tags:
  - name: Default
    description: ''
paths: {}
components:
  schemas: {}
  securitySchemes: {}
